#!/bin/bash
# DSP — Data Sharing Platform (RER ecosystem)
# One-command install for local/demo deployment using published GHCR images.
# Usage: curl -fsSL https://raw.githubusercontent.com/Rural-Environmental-Registry/dsp-core/main/install.sh | sh
#    or: ./install.sh
#
# Prerequisites: Docker 24+ with Docker Compose v2, git, openssl.
# No Java, Node, Maven or application source required — images come from GHCR.
# Only dsp-core (this repo, ~1MB) is cloned, for the demo seed and config templates.

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[DSP]${NC} $1"; }
warn() { echo -e "${YELLOW}[DSP]${NC} $1"; }
error() { echo -e "${RED}[DSP]${NC} $1"; exit 1; }

DSP_VERSION="${DSP_VERSION:-0.0.1-dev}"
DSP_DIR="${DSP_DIR:-$HOME/dsp}"
DSP_PORT="${DSP_PORT:-8026}"
DSP_REGISTRY="${DSP_REGISTRY:-ghcr.io/rural-environmental-registry}"
DSP_CORE_REPO="${DSP_CORE_REPO:-https://github.com/Rural-Environmental-Registry/dsp-core.git}"
DSP_CORE_REF="${DSP_CORE_REF:-main}"

# --- 1. Prerequisites ---
info "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || error "Docker not found. Install: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 not found."
command -v git >/dev/null 2>&1 || error "git not found."
command -v openssl >/dev/null 2>&1 || error "openssl not found."
info "Docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?') OK"

# --- 2. Get dsp-core (config templates + demo seed live here, ~1MB) ---
mkdir -p "$DSP_DIR"
cd "$DSP_DIR"
if [ -f config/db/seed/quickstart ] || [ -d config/db/seed ]; then
  info "dsp-core config present in $DSP_DIR."
elif [ -d dsp-core/.git ]; then
  info "Updating existing dsp-core..."
  git -C dsp-core pull --ff-only origin "$DSP_CORE_REF" 2>/dev/null || warn "git pull failed; using existing checkout."
  cd dsp-core; DSP_DIR="$PWD"
else
  info "Cloning dsp-core ($DSP_CORE_REF)..."
  git clone --depth 1 -b "$DSP_CORE_REF" "$DSP_CORE_REPO" dsp-core
  cd dsp-core; DSP_DIR="$PWD"
fi

# --- 3. Generate .env (demo defaults, random passwords) ---
if [ ! -f .env ]; then
  info "Generating .env (demo mode) with random passwords..."
  PW_DB=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
  PW_GEO=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
  PW_GEOADMIN=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
  cat > .env << EOF
# DSP install.sh — demo mode
DSP_VERSION=${DSP_VERSION}
DSP_REGISTRY=${DSP_REGISTRY}
DSP_GATEWAY_HOST_PORT=${DSP_PORT}
DSP_PUBLIC_BASE_URL=http://localhost:${DSP_PORT}

DSP_DB_NAME=dsp-db
DSP_DB_USER=dsp
DSP_DB_PASSWORD=${PW_DB}
DSP_GEOSERVER_DB_NAME=dsp-geoserver-db
DSP_GEOSERVER_DB_USER=dsp_geo
DSP_GEOSERVER_DB_PASSWORD=${PW_GEO}
DSP_GEOSERVER_ADMIN_USER=admin
DSP_GEOSERVER_ADMIN_PASSWORD=${PW_GEOADMIN}

DSP_BACKEND_CONTEXT_PATH=/dsp-backend
DSP_CORS_ALLOWED_ORIGINS=http://localhost:${DSP_PORT}
# Gateway: Docker DNS + short upstreams (compose defaults)
DSP_RESOLVER=127.0.0.11
DSP_FRONTEND_UPSTREAM=dsp-frontend:8080
DSP_BACKEND_UPSTREAM=dsp-backend:8080
DSP_GEOSERVER_EXHIBITION_UPSTREAM=dsp-geoserver-exhibition:8080
DSP_GEOSERVER_DOWNLOAD_UPSTREAM=dsp-geoserver-download:8080
EOF
  warn "Random passwords generated in .env — review before any non-demo use."
else
  info ".env already exists, keeping it."
fi

# --- 4. Generate docker-compose.release.yml (images only, no build) ---
info "Generating docker-compose.release.yml (GHCR images, no build)..."
cat > docker-compose.release.yml << 'COMPOSE'
# Auto-generated by install.sh — consumes published GHCR images (no build).
services:
  dsp-db:
    image: ${DSP_REGISTRY}/dsp-db:${DSP_VERSION}
    environment:
      POSTGRES_DB: ${DSP_DB_NAME:-dsp-db}
      POSTGRES_USER: ${DSP_DB_USER:-dsp}
      POSTGRES_PASSWORD: ${DSP_DB_PASSWORD:-dsp}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: [dsp-db-data:/var/lib/postgresql/data]
    networks: [dsp_network]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DSP_DB_USER:-dsp} -d ${DSP_DB_NAME:-dsp-db}"]
      interval: 5s
      timeout: 3s
      retries: 20

  dsp-geoserver-db:
    image: ${DSP_REGISTRY}/dsp-geoserver-db:${DSP_VERSION}
    environment:
      POSTGRES_DB: ${DSP_GEOSERVER_DB_NAME:-dsp-geoserver-db}
      POSTGRES_USER: ${DSP_GEOSERVER_DB_USER:-dsp_geo}
      POSTGRES_PASSWORD: ${DSP_GEOSERVER_DB_PASSWORD:-dsp_geo}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: [dsp-geoserver-db-data:/var/lib/postgresql/data]
    networks: [dsp_network]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DSP_GEOSERVER_DB_USER:-dsp_geo} -d ${DSP_GEOSERVER_DB_NAME:-dsp-geoserver-db}"]
      interval: 5s
      timeout: 3s
      retries: 20

  dsp-backend:
    image: ${DSP_REGISTRY}/dsp-backend:${DSP_VERSION}
    environment:
      SERVER_SERVLET_CONTEXT_PATH: ${DSP_BACKEND_CONTEXT_PATH:-/dsp-backend}
      DSP_CORS_ALLOWED_ORIGINS: ${DSP_CORS_ALLOWED_ORIGINS:-http://localhost:8026}
      DSP_GEOSERVER_WFS_BASE_URL: http://dsp-geoserver-download:8080/geoserver/dsp/wfs
      DSP_OBJECT_STORAGE_ENDPOINT: ""
      SPRING_DATASOURCE_URL: jdbc:postgresql://dsp-db:5432/${DSP_DB_NAME:-dsp-db}
      SPRING_DATASOURCE_USERNAME: ${DSP_DB_USER:-dsp}
      SPRING_DATASOURCE_PASSWORD: ${DSP_DB_PASSWORD:-dsp}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      dsp-db: { condition: service_healthy }
    networks: [dsp_network]
    restart: unless-stopped

  dsp-frontend:
    image: ${DSP_REGISTRY}/dsp-frontend:${DSP_VERSION}
    networks: [dsp_network]
    restart: unless-stopped

  dsp-geoserver-exhibition:
    image: ${DSP_REGISTRY}/dsp-geoserver-exhibition:${DSP_VERSION}
    environment:
      PROXY_BASE_URL: ${DSP_PUBLIC_BASE_URL:-http://localhost:8026}/geoserver-exhibition
      GEOSERVER_ADMIN_USER: ${DSP_GEOSERVER_ADMIN_USER:-admin}
      GEOSERVER_ADMIN_PASSWORD: ${DSP_GEOSERVER_ADMIN_PASSWORD:-geoserver}
      DB_HOST: dsp-geoserver-db
      DB_PORT: "5432"
      DB_NAME: ${DSP_GEOSERVER_DB_NAME:-dsp-geoserver-db}
      DB_SCHEMA: dsp
      DB_USER: ${DSP_GEOSERVER_DB_USER:-dsp_geo}
      DB_PASSWORD: ${DSP_GEOSERVER_DB_PASSWORD:-dsp_geo}
      WORKSPACE_NAME: dsp
      DATASTORE_NAME: dsp-geoserver-db
    volumes: [dsp-geoserver-exhibition-data:/var/geoserver/datadir]
    depends_on:
      dsp-geoserver-db: { condition: service_healthy }
    networks: [dsp_network]
    restart: unless-stopped

  dsp-geoserver-download:
    image: ${DSP_REGISTRY}/dsp-geoserver-download:${DSP_VERSION}
    environment:
      PROXY_BASE_URL: ${DSP_PUBLIC_BASE_URL:-http://localhost:8026}/geoserver-download
      GEOSERVER_ADMIN_USER: ${DSP_GEOSERVER_ADMIN_USER:-admin}
      GEOSERVER_ADMIN_PASSWORD: ${DSP_GEOSERVER_ADMIN_PASSWORD:-geoserver}
      DB_HOST: dsp-geoserver-db
      DB_PORT: "5432"
      DB_NAME: ${DSP_GEOSERVER_DB_NAME:-dsp-geoserver-db}
      DB_SCHEMA: dsp
      DB_USER: ${DSP_GEOSERVER_DB_USER:-dsp_geo}
      DB_PASSWORD: ${DSP_GEOSERVER_DB_PASSWORD:-dsp_geo}
      WORKSPACE_NAME: dsp
      DATASTORE_NAME: dsp-geoserver-download-db
    volumes: [dsp-geoserver-download-data:/var/geoserver/datadir]
    depends_on:
      dsp-geoserver-db: { condition: service_healthy }
    networks: [dsp_network]
    restart: unless-stopped

  dsp-gateway:
    image: ${DSP_REGISTRY}/dsp-gateway:${DSP_VERSION}
    ports: ["${DSP_GATEWAY_HOST_PORT:-8026}:8080"]
    environment:
      NGINX_ENVSUBST_FILTER: "^DSP_"
      DSP_BACKEND_CONTEXT_PATH: ${DSP_BACKEND_CONTEXT_PATH:-/dsp-backend}
      DSP_GATEWAY_CACHE_BYPASS: "1"
      DSP_GATEWAY_CACHE_TTL: "10m"
      DSP_RESOLVER: ${DSP_RESOLVER:-127.0.0.11}
      DSP_FRONTEND_UPSTREAM: ${DSP_FRONTEND_UPSTREAM:-dsp-frontend:8080}
      DSP_BACKEND_UPSTREAM: ${DSP_BACKEND_UPSTREAM:-dsp-backend:8080}
      DSP_GEOSERVER_EXHIBITION_UPSTREAM: ${DSP_GEOSERVER_EXHIBITION_UPSTREAM:-dsp-geoserver-exhibition:8080}
      DSP_GEOSERVER_DOWNLOAD_UPSTREAM: ${DSP_GEOSERVER_DOWNLOAD_UPSTREAM:-dsp-geoserver-download:8080}
    depends_on: [dsp-frontend, dsp-backend]
    networks: [dsp_network]
    restart: unless-stopped

volumes:
  dsp-db-data:
  dsp-geoserver-db-data:
  dsp-geoserver-exhibition-data:
  dsp-geoserver-download-data:

networks:
  dsp_network:
    driver: bridge
COMPOSE

COMPOSE_FILE="docker-compose.release.yml"

# --- 5. Pull images ---
info "Pulling DSP images ($DSP_VERSION) from $DSP_REGISTRY..."
if ! docker compose -f "$COMPOSE_FILE" pull; then
  error "Image pull failed. If images are private, log in first:
    echo \$GITHUB_TOKEN | docker login ghcr.io -u <user> --password-stdin"
fi

# --- 6. Bring up databases first, then seed, then the rest ---
info "Starting databases..."
docker compose -f "$COMPOSE_FILE" up -d dsp-db dsp-geoserver-db

info "Waiting for databases to be healthy..."
for i in $(seq 1 40); do
  H=$(docker compose -f "$COMPOSE_FILE" ps dsp-db --format '{{.Health}}' 2>/dev/null || echo "")
  HG=$(docker compose -f "$COMPOSE_FILE" ps dsp-geoserver-db --format '{{.Health}}' 2>/dev/null || echo "")
  [ "$H" = "healthy" ] && [ "$HG" = "healthy" ] && break
  sleep 3
done

# Apply demo seed (quickstart). Mirrors scripts/common.sh:apply_quickstart_seed —
# *_dsp.sql go to dsp-db, *_exhibition.sql go to dsp-geoserver-db (distinct DBs).
SEED_DIR="config/db/seed/quickstart"
if [ -d "$SEED_DIR" ]; then
  DSP_DB_USER=$(grep '^DSP_DB_USER=' .env | cut -d= -f2-)
  DSP_DB_NAME=$(grep '^DSP_DB_NAME=' .env | cut -d= -f2-)
  GEO_DB_USER=$(grep '^DSP_GEOSERVER_DB_USER=' .env | cut -d= -f2-)
  GEO_DB_NAME=$(grep '^DSP_GEOSERVER_DB_NAME=' .env | cut -d= -f2-)

  seed_into() { # <service> <user> <db> <sqlfile>
    docker compose -f "$COMPOSE_FILE" --env-file .env exec -T "$1" \
      psql -q -v ON_ERROR_STOP=1 -U "$2" -d "$3" < "$4" \
      && info "  seeded $(basename "$4") -> $1" \
      || error "seed failed: $(basename "$4") -> $1"
  }

  info "Applying demo seed to dsp-db..."
  seed_into dsp-db "$DSP_DB_USER" "$DSP_DB_NAME" "$SEED_DIR/01_territory_dsp.sql"
  seed_into dsp-db "$DSP_DB_USER" "$DSP_DB_NAME" "$SEED_DIR/02_aoi_dsp.sql"

  info "Applying demo seed to dsp-geoserver-db..."
  seed_into dsp-geoserver-db "$GEO_DB_USER" "$GEO_DB_NAME" "$SEED_DIR/01_territory_exhibition.sql"
  seed_into dsp-geoserver-db "$GEO_DB_USER" "$GEO_DB_NAME" "$SEED_DIR/02_aoi_exhibition.sql"
  warn "Demonstration data only — simplified Brazil geometries, not production."
else
  warn "No demo seed found ($SEED_DIR). Databases start empty."
fi

info "Starting application services..."

# Detect the real container DNS resolver (Docker=127.0.0.11, podman/others differ).
# nginx resolver must point at a working nameserver or upstreams won't resolve.
DETECTED_NS=$(docker compose -f "$COMPOSE_FILE" exec -T dsp-db sh -c 'awk "/^nameserver/{print \$2; exit}" /etc/resolv.conf' 2>/dev/null | tr -d '\r')
# validate it is a bare IPv4 before trusting container output
if printf '%s' "$DETECTED_NS" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
  CUR_NS=$(grep '^DSP_RESOLVER=' .env | cut -d= -f2-)
  if [ "$DETECTED_NS" != "$CUR_NS" ]; then
    info "Container DNS resolver detected: $DETECTED_NS (was $CUR_NS) — updating .env."
    if grep -q '^DSP_RESOLVER=' .env; then
      sed -i "s|^DSP_RESOLVER=.*|DSP_RESOLVER=${DETECTED_NS}|" .env
    else
      echo "DSP_RESOLVER=${DETECTED_NS}" >> .env
    fi
  fi
fi

docker compose -f "$COMPOSE_FILE" up -d

# --- 7. Summary ---
sleep 8
RUNNING=$(docker compose -f "$COMPOSE_FILE" ps --status running -q 2>/dev/null | wc -l | tr -d ' ')
TOTAL=$(docker compose -f "$COMPOSE_FILE" ps -q 2>/dev/null | wc -l | tr -d ' ')
echo ""
info "============================================"
info "  DSP — Data Sharing Platform (demo)"
info "============================================"
info "  URL:      http://localhost:${DSP_PORT}/dsp/"
info "  Version:  ${DSP_VERSION}"
info "  Status:   ${RUNNING}/${TOTAL} services running"
info "  Dir:      ${DSP_DIR}"
info "  Creds:    ${DSP_DIR}/.env"
info ""
info "  Note: GeoServer takes ~1-2 min to finish booting."
info ""
info "  Commands (from ${DSP_DIR}):"
info "    Logs:   docker compose -f ${COMPOSE_FILE} logs -f"
info "    Stop:   docker compose -f ${COMPOSE_FILE} down"
info "    Reset:  docker compose -f ${COMPOSE_FILE} down -v"
info "    Update: DSP_VERSION=x.y.z ./install.sh"
info ""
info "  Real adopter (ETL from a source DB): use ./config.sh + ./setup.sh."
info "============================================"
